version: '3.7'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  backend:
    build: ./trends-be
    ports:
    - "8080:8080"
    volumes:
    - .:/trends-backend
    depends_on:
    - 'mongo'
  frontend:
    build: ./trends-fe
    ports:
    - "3000:3000"
    volumes:
    - .:/trends-frontend
